language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install compass'
  - 'gem install github-markup'
  - 'gem install github-markdown'
  - 'gem install html-pipeline'
  - 'git config --global user.email "mikhail.zyatin@gmail.com"'
  - 'git config --global user.name "Travis CI"'
